name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  Hacktera-contracts-validate:
    name: Run Hacktera-contracts release
    secrets: inherit
    uses: ./.github/workflows/Hacktera-contracts-ci.yaml

  Hacktera-contracts-release:
    name: Run Hacktera-contracts release
    secrets: inherit
    uses: ./.github/workflows/Hacktera-contracts-cd.yaml
    needs: Hacktera-contracts-validate

  Hacktera-frontend-validate:
    name: Run Hacktera-frontend release
    secrets: inherit
    uses: ./.github/workflows/Hacktera-frontend-ci.yaml

  Hacktera-frontend-release:
    name: Run Hacktera-frontend release
    secrets: inherit
    uses: ./.github/workflows/Hacktera-frontend-cd.yaml
    needs: Hacktera-frontend-validate
