name: Pull Request validation

on: [pull_request]


jobs:
  Hacktera-contracts-ci:
    name: Run Hacktera-contracts validation
    uses: ./.github/workflows/Hacktera-contracts-ci.yaml

  Hacktera-frontend-ci:
    name: Run Hacktera-frontend validation
    uses: ./.github/workflows/Hacktera-frontend-ci.yaml

